#!/usr/bin/env bash
name="gdb"
version="14.2"
description="GNU debugger"
source="https://ftp.gnu.org/gnu/gdb/gdb-${version}.tar.xz"
depends="mpfr,gmp"
group="dev.debug"


setup(){
cd $SOURCEDIR
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

