#!/usr/bin/env bash
version="8.2"
name="readline"
depends="glibc"
description="readline kütüphanesi"
source="https://ftp.gnu.org/pub/gnu/readline/${name}-${version}.tar.gz"
groups="sys.apps"

setup(){
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/lib64
}

build(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw"
}

package(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$DESTDIR" install pkgconfigdir="/lib64/pkgconfig"
}
