#!/usr/bin/env bash
version="6.1.0-18"
name="linux-headers"
depends=""
description="temel dağıtım kernel dosyası ve moduller"
source=""
groups="sys.base"
setup()
{
	echo ""
	# deb dosyası indirilir http://ftp.tr.debian.org/debian/pool/main/l/linux/linux-headers-6.1.0-18-amd64_6.1.76-1_amd64.deb
	cd $SOURCEDIR
	wget -O image.deb http://ftp.tr.debian.org/debian/pool/main/l/linux/linux-headers-6.1.0-18-amd64_6.1.76-1_amd64.deb
	# ar x indirilen dosya
	ar x image.deb
	# tar -xf data.tar.xz
	tar -xf data.tar.xz
	# find ./ -iname "*" -exec unxz {} \; komutuyla xz açılır
	

	
}
build()
{
	echo ""
}
package()
{
	cd $BUILDDIR
	cp -prfv lib  ${DESTDIR}/
	cp -prfv usr  ${DESTDIR}/

}


