#!/usr/bin/env bash
version="6.4"
name="ncurses"
depends="glibc"
description="ncurses kütüphanesi"
source="https://ftp.gnu.org/pub/gnu/ncurses/${name}-${version}.tar.gz"
groups="sys.libs"

setup(){
cd $SOURCEDIR
    cp -prf ../$name-$version ../widec
    opts=(--prefix=/usr
          --libdir=/lib64
          --enable-pc-files
          --mandir=/usr/share/man
          --with-manpage-format=normal
          --with-shared
          --with-xterm-kbs=del
          --without-ada
          --with-pkg-config-libdir=/usr/lib64/pkgconfig
          )
    ./configure ${opts[@]}
    cd ../widec
    ./configure ${opts[@]} --enable-widec \
         --with-cxx-binding \
         --with-cxx-shared
}

build(){
    cd ../widec
    make $jobs
    cd ../$name-$version
    make $jobs

}

package(){
    mkdir -p "$DESTDIR/usr/lib/"
    cd ../widec
    make $jobs install DESTDIR=$DESTDIR
    cd ../$name-$version
    make $jobs install  DESTDIR=$DESTDIR

    mkdir -p "$DESTDIR/lib64/" "$DESTDIR/usr/lib64/pkgconfig/" 
    for lib in ncurses ncurses++ form panel menu; do
        if [ ! -f "$DESTDIR/lib64/lib${lib}.so" ]; then
            printf "INPUT(-l%sw)\n" "${lib}" > "$DESTDIR/lib64/lib${lib}.so"
        fi
        if [ ! -f "$DESTDIR/usr/lib64/pkgconfig/${lib}.pc" ]; then
            ln -sv ${lib}w.pc "$DESTDIR/usr/lib64/pkgconfig/${lib}.pc"
        fi
    done
    # some packages look for -lcurses during build
    printf 'INPUT(-lncursesw)\n' > "$DESTDIR/lib64/libcursesw.so"
    if [ ! -f "$DESTDIR"/lib64/libcurses.so ]; then
        ln -sv libncurses.so "$DESTDIR/lib64/libcurses.so"
    fi

    # tic and ticinfo functionality is built in by default
    # make sure that anything linking against it links against libncursesw.so instead
    for lib in tic tinfo tinfow ticw; do
        if [ ! -f "$DESTDIR/lib64/lib${lib}.so" ]; then
            printf "INPUT(libncursesw.so.%s)\n" "${so_ver}" > "$DESTDIR/lib64/lib${lib}.so"
            if [ ! -f $DESTDIR/lib64/lib${lib}.so.${so_ver} ]; then
                ln -sv libncursesw.so.${so_ver} "$DESTDIR/lib64/lib${lib}.so.${so_ver}"
            fi
        fi
        if [ ! -f "$DESTDIR/usr/lib64/pkgconfig/${lib}.pc" ]; then
            ln -sv ncursesw.pc "$DESTDIR/usr/lib64/pkgconfig/${lib}.pc"
        fi
    done
    # legacy binary support
    for lib in libncursesw libncurses libtinfo libpanelw libformw libmenuw ; do
        ln -sv ${lib}.so.${so_ver} "$DESTDIR"/lib64/${lib}.so.5
    done
}
