#!/usr/bin/env bash
name="openssl-1.1"
version="1.1.1u"
url="https://www.openssl.org/source/"
description="The Open Source toolkit for Secure Sockets Layer and Transport Layer Security"
source="https://www.openssl.org/source/openssl-$version.tar.gz"
group="dev.libs"
# for pod2man
export PATH=$PATH:/usr/bin/core_perl

setup(){
	#cp -prfv $PACKAGEDIR/update-certdata.sh /tmp/bps/build/
	
../${name}-${version}/Configure --prefix=/usr \
        --openssldir=/etc/ssl \
        --libdir=lib64/openssl-1.1 \
        shared linux-x86_64
}

build(){
    make depend $jobs
    make $jobs
}

package(){
    mkdir -p "${DESTDIR}/etc/ssl/" "${DESTDIR}/sbin/"
    make DESTDIR="${DESTDIR}" \
    install_sw $jobs
    rm -rf $DESTDIR/{etc,usr/bin}
    mv $DESTDIR/usr/include/openssl $DESTDIR/usr/include/openssl-1.1
    sed -e 's|/include$|/include/openssl-1.1|' -i "$DESTDIR"/usr/lib64/openssl-1.1/pkgconfig/*.pc
    mkdir -p $DESTDIR/etc/ld.so.conf.d/
    echo "/usr/lib64/openssl-1.1" > $DESTDIR/etc/ld.so.conf.d/openssl-1.1.conf
}

